# Generated by Django 3.1.7 on 2021-03-07 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20210307_0206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='room',
        ),
        migrations.AddField(
            model_name='room',
            name='chat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.chat'),
        ),
    ]
